name: username_generator
description: A simple library for generating random and seedable username for emails or user forms 
version: 1.2.3
homepage: https://github.com/prikeshsavla/username_generator.dart
repository: https://github.com/prikeshsavla/username_generator.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
